### ISSUE TITLE
Improvement to logs

### ISSUE THREAD

**Issue by ryan13mt** [painebenjamin/app.enfugue.ai#11]
I saw you are opening issues and assigning them to a release. An improvement to the logs would be very beneficial to help you problem solving other users issues. And also competent people might try to solve it themselves. 

Currently logs are filled with repeating stuff and the errors seem to be caught and listing them as INFO. 

Can you filter out the "non-important" repeating logs and marking the errors as ERROR?

![image](https://github.com/painebenjamin/app.enfugue.ai/assets/6053618/cf9fb3f3-e266-4669-8907-69b29ad0f886)

**Comment by painebenjamin** [comment]
Thankfully I thought at least a little bit ahead and this is configurable - it's just not _easily_ configurable for people. We'll make the default configuration more sane.

Exact steps for changing this going forward:
1. Change log level in [config/production/logging.yml](https://github.com/painebenjamin/app.enfugue.ai/blob/main/config/production/logging.yml) (WARN or ERROR is probably best)
2. Re-build using `make`

The packaged configuration can be changed on-the-fly if there's ever a reason to - edit in `/enfugue/config/` in the archive directory for the binary distribution or the `site-packages` directory if installed via `pip`.

**Comment by ryan13mt** [comment]
The error highlighted above won't be shown then right? cause its being marked as INFO currently

**Comment by painebenjamin** [comment]
The message at `INFO` is actually the message of storing the error in the database - which is itself not an error, so in a perfect world that _should_ be hidden and we should be reviewing the actual error message.

However, you raise a very good point - the actual error message isn't in there when it should be. I believe I am eating the error message during the diffusion process without ever logging it, instead only returning it back to the main API process. Added a 'bug' label to this so this gets fixed, too.

Relevant code location for the eating of diffusion exceptions is [here](https://github.com/painebenjamin/app.enfugue.ai/blob/main/src/python/enfugue/diffusion/process.py#L346).

**Comment by painebenjamin** [comment]
Thank you for the numerous suggestions @ryan13mt - logging is much improved as of 0.1.2!
