### ISSUE TITLE
Default username/password does not work on fresh install in Windows

### ISSUE THREAD

**Issue by mKevinl2** [painebenjamin/app.enfugue.ai#12]
Installed and successfully ran server according to directions. Did not download any models or attempt any generations yet (waiting on ability to point enfugue to my already downloaded models). Browsed CivitAi from enfugue (still did not download anything). Then checked the box for Under System>"Use Authentication".
Attempted to use the default "enfugue"/ "password" as listed in directions, but that failed. Had to reset the password using the text file in the cache to make it work.

**Comment by painebenjamin** [comment]
Thank you very much for the report. I'm glad to know the reset worked for you.

I made a mistake, and the default password is actually `enfugue`. Very sorry about that. 

Relevant initialization configuration details are [here](https://github.com/painebenjamin/app.enfugue.ai/blob/main/config/production/server.yml#L56).

**Comment by mKevinl2** [comment]
Good to know! I see you already updated the directions, so that should be all for this.
