### ISSUE TITLE
Add NSFW filter for CivitAi browsing

### ISSUE THREAD

**Issue by mKevinl2** [painebenjamin/app.enfugue.ai#13]
Browsing CivitAi from enfugue allows NSFW models, LORA's, etc and their images to be visible by default. Directly on their site, such things are blurred or removed entirely from what is viewable without logging in first.

**Comment by painebenjamin** [comment]
Hello @mKevinl2, thank you for the report!

At the moment, NSFW content is shown when you disable the safety checker. When the checker is enabled, NSFW content is not shown in the UI. I can see how there would be a desire to not see NSFW content even with the checker disabled, though, so I will add a checkbox in the filter options.

**Comment by painebenjamin** [comment]
Added with 0.2.0
