### ISSUE TITLE
Portable installation doesn't work

### ISSUE THREAD

**Issue by LuisBurdallo** [painebenjamin/app.enfugue.ai#134]
![Snippet_004](https://github.com/painebenjamin/app.enfugue.ai/assets/33180658/ea564680-1935-4768-9c9a-618781ce40bd)

**Comment by painebenjamin** [comment]
Hi @LuisBurdallo, thank you for the report!

When you posted this, there was a fixed package being uploaded to the releases page with a bug fix for #131, and the package was unavailable at that time. It's finished uploading now. I'm looking into ways to release patch updates that will avoid this in the future, but for now, you should be able to re-run the installer and it should download. Please let me know if that doesn't work!

**Comment by LuisBurdallo** [comment]
Downloading now. Thanks you so much!

**Comment by painebenjamin** [comment]
Glad it worked for you!
