### ISSUE TITLE
Enfugue autodownloads SD 1.5 without needing to when different model is specified

### ISSUE THREAD

**Issue by mKevinl2** [painebenjamin/app.enfugue.ai#14]
I found the system>installation file management area, tried adding a checkpoint I already had successfully. Then went to the model manager and created a new model with my checkpoint set. Then tried to generate my first image. Server took waaay too long for something that was already downloaded and my PC was acting slow; realized in task manager that the disk usage was 100% so I stopped everything and investigated. Then found out that enfugue had gone and downloaded 1.5 to the cache area anyway despite me never asking it to (nor should it have needed to with my other model already specified first).

**Comment by painebenjamin** [comment]
Did you happen to be inpainting?

For a lot of technical reasons, a regular checkpoint and an inpainting checkpoint are not interchangeable - and in order to create an inpainting checkpoint from a non-inpainting one, it is a three-modeled math equation between the base SD 1.5 checkpoint, your custom checkpoint, and the SD 1.5 Inpainting checkpoint. If the system can't find those checkpoints when it goes to create the inpainting checkpoint, it will download them - that's the entire reason the base models are required in the first place.

Relevant call to merge checkpoints: https://github.com/painebenjamin/app.enfugue.ai/blob/main/src/python/enfugue/diffusion/manager.py#L1336

Checkpoint Merger:
https://github.com/painebenjamin/app.enfugue.ai/blob/main/src/python/enfugue/diffusion/util.py#L74 (taken almost verbatim from A1111)

**Comment by mKevinl2** [comment]
> Did you happen to be inpainting?

No, I used deliberate_v2.safetensors as the given checkpoint. That should be a complete replacement of the SD 1.5 checkpoint, correct? At least that's how I've perceived it working in other UI's.

**Comment by painebenjamin** [comment]
Sorry, that was very unclear - I'm using "inpainting" to mean any kind of inference that has a mask. People who are used to SD expect to have to switch checkpoints between inpainting and not, there is none of that in Enfugue - I switch to inpainting when it is needed. It is needed for far more than just the obvious, too - the only time you are _not_ inpainting is if you are using just text inference (basic `txt2img`) or have an image that covers the entire canvas from corner to corner (basic `img2img`). Everything else is inpainting - so if you put an image on the canvas that has gaps on the sides, or has transparency, or you draw a mask to inpaint directly on an image, or there are multiple nodes on the canvas, then I have to inpaint to fill in the gaps. So if any of those things were true, you _were_ inpainting, whether you knew it or not.

**Comment by mKevinl2** [comment]
> Sorry, that was very unclear - I'm using "inpainting" to mean any kind of inference that has a mask... So if any of those things were true, you _were_ inpainting, whether you knew it or not.

Thank you for the clarification. However, by this definition I was still _not_ inpainting. I simply specified the model with the safetensor checkpoint, typed some simple text (basic txt2img) and clicked go (well technically "enfugue").

**Comment by painebenjamin** [comment]
Okay. Thank you very much for the info - one final question. Did you configure the model using the "add model" dialogue, or were you simply entering the checkpoint name in the model picker? I apologize if the question is dumb, but I've noticed people weren't quite understanding the difference between checkpoint files and configured models - I need much better hinting in the UI around that.

**Comment by mKevinl2** [comment]
> Okay. Thank you very much for the info - one final question. Did you configure the model using the "add model" dialogue, or were you simply entering the checkpoint name in the model picker?

I used the add model dialogue, but for clarity so we know we're on the same page- I'll list a step by step of what I did:
1. System>Installation>Checkpoints>Manage>upload file -- Successfully "uploaded" the deliberate_v2.safetensor file (is this actually a copy to cache function?)
2. Models>New Model>selected Deliberate_v2.safetensor as the checkpoint, named the model simply "DeliberateV2", clicked "Submit"
3. Typed "Deliberate" in the top left searchbox and noticed the newly created model was now there as the only option; clicked it. Now it shows as how I named it when I click anywhere else.
4. Typed simple text prompt on far right sidebar
5. Clicked Enfugue
6. ...
7. Realized abnormal time + disk usage; clicked the stop button in top right of canvas area
8. Right clicked Enfugue in system tray>Quit
9. Investigated and found SD 1.5 in C: drive cache folder
10. Wished the cache folder was in the same folder as where I installed Enfugue (F: drive) since this operation filled the C: drive and started stalling the OS when disk usage was maxed.

> I've noticed people weren't quite understanding the difference between checkpoint files and configured models - I need much better hinting in the UI around that.
I almost didn't understand this, but I caught on to the idea when I read that checkpoints + LORA's and other things people combine have different sizes internally and the model configuration in Enfugue's backend basically keeps everything only connected with what works/ is compatible with each other. I agree with this design for Enfugue's target audience, though as you mentioned, more UI hinting is needed.

**Comment by ChadDa3mon** [comment]
I'd like to chime in here instead of opening a new issue, but let me know if you'd prefer a new issue. I installed this on my server which already has A1111 installed. I've already got dozens of models downloaded and I wanted to point Enfugue to them. It looks like it's using ~/.cache/enfugue/models so I just made it a symlink to my models folder. 

I can't see any of them under "Models" (nor can I figure out how to add them) but if I go to **Settings -> Installation Manager -> Models** they do show up there. I've still got no idea how to actually select one of my existing models...

**Comment by painebenjamin** [comment]
Hey @thesomeotherguy,

Thank you for the report! It definitely should't be downloading the base model unless:
1. You tried generating an image without selecting any other models
2. You are trying to inpaint and I need to create an inpainting checkpoint.

Obviously that's not very helpful to you if it is clearly downloading it despite what I think it should be doing. Can you perhaps share with me the configuration of the model you tried to compiled TRT engines with?

With respect to the one hour cap - it actually starts after any initial downloads. When downloading, a `keepalive` is set that stops it from timing out, and then turned off when it starts the actual compilation.

Relevant code for the developers/curious:

1. [Creating inpainting checkpoint](https://github.com/painebenjamin/app.enfugue.ai/blob/main/src/python/enfugue/diffusion/manager.py#L1334)
2. [Keepalive during regular initial checkpoint download](https://github.com/painebenjamin/app.enfugue.ai/blob/main/src/python/enfugue/diffusion/manager.py#L1129)

**Comment by painebenjamin** [comment]
This has been fixed in the latest release. Thank you!
