### ISSUE TITLE
No output from starting up?

### ISSUE THREAD

**Issue by ChadDa3mon** [painebenjamin/app.enfugue.ai#19]
I'm not sure if it's working or not, firing this up on my ubuntu server using `enfugue run` doesn't display anything. There's no indication if it's working, and there's no errors either. 

FWIW, I installed this using your conda instructions from the .yaml file you provided.

**Comment by painebenjamin** [comment]
Thank you for the report!

No news is good news in this case (at least in relation to whether or not it ran - your other issue still applies.) However that's definitely not a great user experience, so I'm using this issue to add some output when it's running.

**Comment by painebenjamin** [comment]
@ChadDa3mon Thanks again - there is now visible output as of 0.1.2!
