### ISSUE TITLE
Auto-Launch Browser once Server is Responsive

### ISSUE THREAD

**Issue by SoftologyPro** [painebenjamin/app.enfugue.ai#20]
Downloaded and unzipped the 2 zip files.
Ran the exe.  System tray icon appears.
Opened `app.enfugue.ai` in Chrome.
No options or buttons or menus etc.
![image](https://github.com/painebenjamin/app.enfugue.ai/assets/47686889/418dac46-4e9d-4781-9112-b38a1bc6fdb2)

**Comment by RandomKaos999** [comment]
Seems to be the same thing as I get, I found this under the closed issues... https://github.com/painebenjamin/app.enfugue.ai/issues/7
Just waiting for a new window release with that fix included. I did try installing with conda, but didnt get anywhere on the 1st hurdle, but didnt try very hard if im honest !

**Comment by painebenjamin** [comment]
Thank you @RandomKaos999, this issue should be resolved as of 0.1.2!

**Comment by SoftologyPro** [comment]
1.0.2 is worse.
I run the exe and it shows in the system tray.
When I open app.enfugue.ai in chrome I get a 404
![image](https://github.com/painebenjamin/app.enfugue.ai/assets/47686889/f00b5817-4e63-44b4-8955-6faebafd752e)

**Comment by painebenjamin** [comment]
Hi @SoftologyPro,

Thank you for the feedback. Can you confirm that you're accessing `https://app.enfugue.ai:45554/`? All of those details need to be present for your browser to communicate with the server correctly - `https` should be specified to ensure it is using SSL encryption, and the port `45554` must be specified or else your computer will use the default port (`443` for SSL connections.)

The landing page `my.enfugue.ai` should forward you directly to `https://app.enfugue.ai:45554/` to avoid the confusion of ports.

If that still doesn't solve it, and the server is sitting happily without reporting any issues, then the likely situation is that your firewall is restricting access to your network. See [here](https://github.com/painebenjamin/app.enfugue.ai#troubleshooting) for a bit of information on modifying the Windows Firewall.

**Comment by SoftologyPro** [comment]
OK, specifying the port works.  https://app.enfugue.ai:45554/
A suggestion would be to auto-launch the web page once the exe is done loading.

**Comment by painebenjamin** [comment]
Whoa, that's an **AWESOME** idea. I love it. I'm co-opting this issue to make that happen.

**Comment by lennartbrandin** [comment]
Another nice addition would be a link inside the console output, this is the way a1111's way of handling it. 
I would also like auto open browser to be configurable (opt out if it feels good).

**Comment by painebenjamin** [comment]
This has been implemented in the latest release. Thank you!
