### ISSUE TITLE
Help or Examples with Inpainting?

### ISSUE THREAD

**Issue by ChadDa3mon** [painebenjamin/app.enfugue.ai#25]
I seem to recall some sort of video or animated gif in your reddit post on this, but I can't find it. I'm trying to do some basic inpainting and it's not working. I've got no idea if I'm doing this right or not. 

I started out just generating a cat with an apple. Then I've clicked the `Use for Inpainting` option, which gives me the interface. I made a circle on the wall and changed the prompt to "a clock" or "Add a clock on the wall" and neither seem to do anything. 

Do you have any documentation somewhere on this?

**Comment by painebenjamin** [comment]
I do not have documentation yet - that's going to go into a more intermediate guide on the wiki

That's not _quite_ how inpainting works. Enfugue uses the same inpainting system that base Stable Diffusion does, so other guides/tips/tricks you can find online apply. The biggest advice I can give is this: the prompt describes the _entire picture_, not just the shaded area. The shaded area only controls which parts of the image are allowed to be destroyed in the final image.

Try and think of it this way: you asked for a clock. Stable Diffusion looks in it's memory and thinks of what a clock looks like. It then looks at the rest of your image, and compares it to images it knows of clocks. Does your image resemble those images? Probably not, your image probably resembles something else entirely. When the image you provide and the prompt you ask for are vastly different, Stable Diffusion behaves less predictably than if your prompt and the image align - so it sort of threw it's hands up and decided that it made more sense for that space on the wall to just be filled with _more wall_.

So a starting point is to ask it for what you actually want - `person sitting in chair, clock on the wall`, for instance.
