### ISSUE TITLE
 infinite Initializing…

### ISSUE THREAD

**Issue by AbramovS1** [painebenjamin/app.enfugue.ai#33]
Makes one picture and after infinite Initializing…

**Comment by painebenjamin** [comment]
Hi @AbramovS1,

Thank you very much for the report! It's interesting that it managed to make one image, but stopped right after. It doesn't make much sense for it to try to do that, so you may have uncovered a new bug.

If you're able, could you potentially share your log files? They are located at `~/.cache/enfugue.log` and `~/.cache/enfugue-engine.log`, where `~` is your home directory - `/home/username` on Linux, or `C:\Users\username\` on Windows, substituting in your drive letter and username as needed.

Thank you!

**Comment by AbramovS1** [comment]
Without problems
[enfugue-engine.log](https://github.com/painebenjamin/app.enfugue.ai/files/11924348/enfugue-engine.log)
[enfugue.log](https://github.com/painebenjamin/app.enfugue.ai/files/11924349/enfugue.log)

**Comment by AbramovS1** [comment]
> Hi @AbramovS1,
> 
> Thank you very much for the report! It's interesting that it managed to make one image, but stopped right after. It doesn't make much sense for it to try to do that, so you may have uncovered a new bug.
> 
> If you're able, could you potentially share your log files? They are located at and , where is your home directory - on Linux, or on Windows, substituting in your drive letter and username as needed.`~/.cache/enfugue.log``~/.cache/enfugue-engine.log``~``/home/username``C:\Users\username\`
> 
> Thank you!

Funny the problem was solved after running as administrator

**Comment by AbramovS1** [comment]
> Hi @AbramovS1,
> 
> Thank you very much for the report! It's interesting that it managed to make one image, but stopped right after. It doesn't make much sense for it to try to do that, so you may have uncovered a new bug.
> 
> If you're able, could you potentially share your log files? They are located at `~/.cache/enfugue.log` and `~/.cache/enfugue-engine.log`, where `~` is your home directory - `/home/username` on Linux, or `C:\Users\username\` on Windows, substituting in your drive letter and username as needed.
> 
> Thank you!

And the problem came back again after a couple of generations...

**Comment by painebenjamin** [comment]
Thank you - glad to hear it worked, then sorry to hear it stopped working.

There are a few things that could be going on at 

1. Check the engine logs in the UI under `System`. The most recent messages can help indicate what it's doing if it's been waiting a while - for example, if you use a new ControlNet that wasn't used before, Enfugue will have to download some data so it will take a little longer than normal.
2. There is a strict 90 second no-communication timeout on the engine process. In theory, if anything ever gets "stuck," it _should_ kill any diffusion process and tell you in the UI that it's done so (it will say "Invocation Timeout".) If it's been longer than 90 seconds and nothing seems to be happening, it usually means that something else is going on, like the aforementioned download.
3. The icon in the header that goes between gray, green and yellow can be clicked when it is green or yellow. That should issue a hard stop to anything, and you can try agian.

**Comment by painebenjamin** [comment]
Also - I'm wondering if there might be a front-end issue going on here, too. Next time it happens, it would be awesome if you could open the console and take a screenshot of what you find there (if anything) - on most browsers this is achieved by pressing F12.

**Comment by AbramovS1** [comment]
> Also - I'm wondering if there might be a front-end issue going on here, too. Next time it happens, it would be awesome if you could open the console and take a screenshot of what you find there (if anything) - on most browsers this is achieved by pressing F12.

When generating, it always throws errors


index.mjs:1  Error in API request get undefined Object undefined undefined
(anonymous) @ index.mjs:1
:45554/api/:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
index.mjs:1  Error in API request get /invocation Object undefined undefined
(anonymous) @ index.mjs:1
index.mjs:1  
(anonymous) @ index.mjs:1
:45554/api/invocation:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
status.mjs:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at StatusView.updateStatus (status.mjs:1:1575)
    at index.mjs:1:7464
index.mjs:1  Error in API request get undefined Object undefined undefined
(anonymous) @ index.mjs:1
:45554/api/:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
status.mjs:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at StatusView.updateStatus (status.mjs:1:1575)
    at index.mjs:1:7464
index.mjs:1  Error in API request get /invocation Object undefined undefined
(anonymous) @ index.mjs:1
index.mjs:1  
(anonymous) @ index.mjs:1
:45554/api/invocation:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
index.mjs:1  Error in API request get undefined Object undefined undefined
(anonymous) @ index.mjs:1
:45554/api/:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
index.mjs:1  Error in API request get /invocation Object undefined undefined
(anonymous) @ index.mjs:1
index.mjs:1  
(anonymous) @ index.mjs:1
:45554/api/invocation:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
status.mjs:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at StatusView.updateStatus (status.mjs:1:1575)
    at index.mjs:1:7464
index.mjs:1  Error in API request get undefined Object undefined undefined
(anonymous) @ index.mjs:1
:45554/api/:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
status.mjs:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at StatusView.updateStatus (status.mjs:1:1575)
    at index.mjs:1:7464
index.mjs:1  Error in API request get /invocation Object undefined undefined
(anonymous) @ index.mjs:1
index.mjs:1  
(anonymous) @ index.mjs:1
:45554/api/invocation:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
