### ISSUE TITLE
Cannot install in linux

### ISSUE THREAD

**Issue by JohnTesla** [painebenjamin/app.enfugue.ai#38]
Cannot install in linux - linux support , install - not  works

**Comment by painebenjamin** [comment]
Hi @JohnTesla, thank you for the report! Sorry to hear you're having problems.

Can you describe a little bit about what you mean by "not works?" Are you having difficulties extracting the package, or is nothing working when you try to use the app?

**Comment by painebenjamin** [comment]
Hi there, it's been some time so I'm going to assume you're no longer experience the issue or have moved on. Either way, I'm going to close the issue; go ahead and re-open a new one again if you experience any other difficulties.
