### ISSUE TITLE
"Could not initialize NNPACK! Reason: Unsupported hardware."

### ISSUE THREAD

**Issue by TrainerSnow** [painebenjamin/app.enfugue.ai#39]
After about 21 minutes and 30 seconds the server outputs
`[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.`
The web interface is then stuck on the 21m and 30s countup.

enfugue.log: https://pastebin.com/z17dbdG6

Specs:
```
cpu:                                                            
                       Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz, 1866 MHz
                       Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz, 2450 MHz
                       Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz, 2772 MHz
                       Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz, 2733 MHz
monitor:
                       IIYAMA PL2730H
                       A19-2A
graphics card:
                       nVidia GP107 [GeForce GTX 1050]
                       Intel 2nd Generation Core Processor Family Integrated Graphics Controller
``

**Comment by painebenjamin** [comment]
Hello!

Could you please confirm the version of your graphics driver? [Here](https://nvidia.custhelp.com/app/answers/detail/a_id/2039/~/how-do-i-determine-which-nvidia-display-driver-version-is-currently-installed) is some documentation from Nvidia regarding how to locate this information.

Specifically, if it's less than `452.39`, please ensure you've updated to the latest and try again. Your hardware should be supported based on Nvidia's [compatibility Matrix](https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html) here - the 1050 has a Pascal architecture with CUDA 6.1 Compute capability.

I do want to warn you though, with only 2Gb of VRAM on the 1050, you will likely have a lot of difficulty trying to use the original Stable Diffusion checkpoint. You may be able to use a more fine-tuned checkpoint (they usually clock in near that 2GB mark), but it will be slow for you. Very sorry about that - I am working to improve memory usage but there are some hardware limitations that will be difficult to overcome. I'm currently working with some cloud service provides to get Enfugue up there - that may end up being an overall better experience for you.

Thank you for the report!

**Comment by TrainerSnow** [comment]
Hi,
thanks for quick response. My Nvidia driver version seems to be `525.125.06`:
```
$ nvidia-smi
Sun Jul  2 19:49:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   56C    P0    N/A /  70W |    555MiB /  2048MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
``

**Comment by painebenjamin** [comment]
How are you currently running Enfugue? I ask because you have CUDA 12 installed; `enfugue` was designed with `11.7` in mind. `12` likely causes issues, but if you're running `enfugue` in `conda` or through the pre-packaged bundle, in theory it would be fine that you have a global `12` installed.

**Comment by TrainerSnow** [comment]
Hi, I installed Enfugue using your `As Easy as Possible: Self-Contained Executable` installation guide.
I downgraded CUDA to 11.7:
```
$ nvidia-smi
Mon Jul  3 20:28:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   59C    P0    N/A /  70W |    389MiB /  2048MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
, sadly still getting the same warning message.

Would it be worth a try setting it up in a conda environment?

**Comment by TrainerSnow** [comment]
Update: Running it in a Miniconda environment solved the issue!

(I'm unabled to run due to my hardware limitation but thats on me ;))

**Comment by painebenjamin** [comment]
I'm so glad that got it working! Thanks so much for trying, that's helpful to know.

I'm trying to get more recreateable Windows builds as we speak so these things can be tracked down better, and part of that is getting it to build somewhere other than my computer, which hopefully will come along with better understanding of the overall dependency map.

It's real slow going though:
![image](https://github.com/painebenjamin/app.enfugue.ai/assets/57536852/45accfc9-108d-4014-b465-d9b5f425ec19)
Have to wait half an hour just to realize I made a typo or forgot some package. 💤

Thanks again!!!
