### ISSUE TITLE
Installation compessed files broken

### ISSUE THREAD

**Issue by PatheticProgrammingPerson** [painebenjamin/app.enfugue.ai#6]
The file `enfugue-server-0.1.0-win64.zip.002` isn't recognised by 7Z. 

`enfugue-server-0.1.0-win64.zip.001` works fine.
 
`enfugue-server-0.1.0-win64.zip.002` is recognised as a `.002` file, instead of a `zip` file, giving a `Cannot open file as archive` error when trying to unzip it.

**Comment by painebenjamin** [comment]
Hello!

You do not need to extract the second ZIP file. If 7-zip recognized and extracted the first file and did not give you an error saying "Unexpected End of Data," then it found the second file and automatically appended it to the first to make a complete ZIP archive.
