### ISSUE TITLE
Windows MIME Types are not consistent - force *.mjs `Content-Type` header to `application/javascript`

### ISSUE THREAD

**Issue by cyco-creates** [painebenjamin/app.enfugue.ai#7]
I'm accessing enfuge through :45554 port but I'm getting black/blank workspace.
Please advise.

![enfuge](https://github.com/painebenjamin/app.enfugue.ai/assets/113450406/ea98a0db-fc12-4e13-a7c2-dd18c455ac2a)

**Comment by victorvalenzuela** [comment]
Me too

**Comment by painebenjamin** [comment]
Thank you for the report. If you haven't already, can you please make sure you've cleared your cache/cookies and try again? I know it's annoying, but that will help rule out transient errors.

If that doesn't work, it would be lovely if you could try reloading the page but having the console enabled by pressing `F12`. On Chrome it will usually appear on the side, and on Firefox on the bottom. If you could take a screenshot of anything that shows up in that log, it would be very helpful.

![image](https://github.com/painebenjamin/app.enfugue.ai/assets/57536852/305e5260-b34f-4538-ad21-a938265de390)

Thanks again!

**Comment by metadreamx** [comment]
Hey, I'm seeing this error 
![Screenshot 2023-06-28 131316](https://github.com/painebenjamin/app.enfugue.ai/assets/93571019/a669ae7a-0e63-4c49-8a79-8f85ee6df33e)

**Comment by painebenjamin** [comment]
Beautiful, that's exactly what I needed to know, and enough to identify and fix the bug. Thank you so much!
