### ISSUE TITLE
TensorRT Linux Compatibilty with H100

### ISSUE THREAD

**Issue by ConsceIeratus** [painebenjamin/app.enfugue.ai#70]
![image](https://github.com/painebenjamin/app.enfugue.ai/assets/135762418/5b57ad33-13b6-4868-a790-f7110879de63)

**Comment by painebenjamin** [comment]
Thank you very much for the report.

Uou can try using a newer version of CUDA and Torch. The default CUDA version (11.7) has worked best for those that have tried it so far, much better than other CUDA versions - but you're the first person I know of that's trying TensorRT on a Hopper GPU, so you may have luck where I didn't.

It looks like you're using Conda, so you can upgrade CUDA to 12 like this:

```sh
conda activate enfugue
conda install cuda-toolkit=12.1.1 -c nvidia/label/cuda-12.1.1
pip install torch==2.1.0.dev20230820+cu121 --extra-index-url https://download.pytorch.org/whl/nightly/cu121
```
 
You can then give it another shot and see if things work better for you. I would love it if you would let me know how that works for you, I'm still trying to nail down what works and doesn't!

Thank you!

**Comment by painebenjamin** [comment]
That would be **incredible**, @ArasAyen. I spent some time today looking into PAYG options for H100's and pretty quickly realized I wasn't going to find anything remotely within budget. There are a *lot* of flags and options that can be changed with both the ONNX export and the TRT compile, so I'm reasonably confident it'll be a matter of changing flags, compiling, testing, and repeating until I find what sticks.

Thank you so much for the offer! Shoot me an e-mail at benjamin@enfugue.ai and we can work out details.
