### ISSUE TITLE
Why does SDXL require 12GB of VRAM?

### ISSUE THREAD

**Issue by ninjasaid2k** [painebenjamin/app.enfugue.ai#90]
Why does SDXL require 12GB of VRAM? Is this using the same optimizations in speed and memory usage for running SDXL as [Foocus](https://github.com/lllyasviel/Fooocus)?

**Comment by painebenjamin** [comment]
Hello @ninjasaid2k!

Can you let me know what version of ENFUGUE you are using? As of v0.2.4 SDXL will work in less than 8GB of VRAM - it will take more if it is available for speed, though. In the Settings menu, check the `Use Sequential Model Loading` to get the most bang for your buck when it comes to VRAM.

![image](https://github.com/painebenjamin/app.enfugue.ai/assets/57536852/9db3d009-371c-48dc-aab0-d9edbe6fa5dc)

**Comment by ninjasaid2k** [comment]
> Can you let me know what version of ENFUGUE you are using? As of v0.2.4 SDXL will work in less than 8GB of VRAM - it will take more if it is available for speed, though. In the Settings menu, check the `Use Sequential Model Loading` to get the most bang for your buck when it comes to VRAM.

I am using v0.2.4, it said that I need 12GB of VRAM to run SDXL on your app.

**Comment by painebenjamin** [comment]
You're right, I did say that! That message was put in right when SDXL was released and hasn't been updated in some time, so thank you for pointing that out.
